Nível 1: Básico — Faturamento Semanal e Filtros
Sua primeira tarefa envolve analisar o volume de vendas de uma única loja durante uma semana comercial.


 Passo 1: Crie um array unidimensional chamado pecas_vendidas contendo o histórico diário da semana: [150, 120, 90, 210, 300, 250, 180] utilizando a função np.array().

In [ ]:
import numpy as np

print('Versão do NumPy:', np.__version__)


Versão do NumPy: 2.1.3


In [ ]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
print('Peças vendidas na semana', pecas_vendidas)



Peças vendidas na semana [150 120  90 210 300 250 180]


Passo 2: A gerência pediu uma estimativa rápida de faturamento. Sabendo que o preço médio de cada peça é de R$ 50,00, crie um novo array multiplicando o array original por 50. Observe como o NumPy aplica essa operação matemática a todos os elementos de uma só vez, sem a necessidade de escrever laços de repetição (operações vetorizadas).

In [ ]:
pecas_vendidas= np.array([150, 120, 90, 210, 300, 250, 180])
print(' A estimativa do faturamento foi:', pecas_vendidas * 50)

 A estimativa do faturamento foi: [ 7500  6000  4500 10500 15000 12500  9000]


Passo 3: Identifique os dias de pico. Crie uma máscara booleana para filtrar e extrair apenas os dias em que a loja vendeu estritamente mais de 200 peças (ex: pecas_vendidas > 200).

In [ ]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
print('Os dias de pico foram:', pecas_vendidas > 200)

Os dias de pico foram: [False False False  True  True  True False]


Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema
Agora você precisa compilar os dados de três filiais diferentes ao longo de quatro dias. A matriz resultante deverá representar as lojas nas linhas e os dias nas colunas.



Passo 1: Crie uma matriz 2D a partir das seguintes listas para representar as vendas: Loja A: [200, 220, np.nan, 250] (Houve uma falha no sistema no 3º dia, gerando um valor não-número). Loja B: [150, 180, 160, 190] Loja C: [300, 310, 290, 330]

In [ ]:
LojaA= [200, 220, np.nan, 250]
LojaB= [150, 180, 160, 190]
LojaC= [300, 310, 290, 330]

print(np.array([LojaA, LojaB, LojaC]))

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


 Passo 2: Calcule o total de peças vendidas por cada loja (agregando pelas linhas). Para isso, aplique a função de soma especificando o parâmetro axis=1.

In [ ]:
vendas_filiais = np.array([LojaA, LojaB, LojaC])
total_por_loja = np.sum(vendas_filiais, axis=1)
print('Total de peças vendidas por loja:', total_por_loja)

Total de peças vendidas por loja: [  nan  680. 1230.]


Passo 3: A diretoria quer saber a média diária geral da rede. Como os dados reais frequentemente possuem lacunas, calcule a média utilizando a função do NumPy que ignora os valores nan. Se você usar a média normal, o resultado será contaminado e invalidará o relatório.

In [ ]:
media_diaria_geral = np.nanmean(vendas_filiais)
print('Média diária geral da rede (ignorando NaNs):', media_diaria_geral)

Média diária geral da rede (ignorando NaNs): 234.54545454545453


 Passo 4: A meta diária de cada loja é vender 200 peças. Utilize a função np.where() para criar uma nova matriz condicional, onde os valores maiores ou iguais a 200 sejam substituídos pelo texto 'Meta Atingida', e os valores inferiores sejam substituídos por 'Abaixo'.

In [ ]:
metas_lojas = np.where(vendas_filiais >= 200, 'Meta Atingida', 'Abaixo')
print('Matriz condicional de metas das lojas:\n', metas_lojas)

Matriz condicional de metas das lojas:
 [['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


Nível 3: Avançado — Categorização e Destaques de Marketing
Nesta etapa final, você fará uma análise focada no perfil das vendas e no sucesso das campanhas publicitárias.



Passo 1: Para simular uma base de clientes, utilize o gerador moderno com uma semente fixa (np.random.default_rng()) para que os resultados sejam reproduzíveis. Crie uma amostra com 50 vendas sorteadas entre as opções ['Eletrônicos', 'Roupas', 'Casa'].

In [ ]:
rng = np.random.default_rng(seed=42) # Usando uma semente fixa para reprodutibilidade
opcoes_venda = ['Eletrônicos', 'Roupas', 'Casa']
amostra_vendas = rng.choice(opcoes_venda, size=50)
print('Amostra de 50 vendas:\n', amostra_vendas)

Amostra de 50 vendas:
 ['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Casa' 'Casa' 'Casa'
 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Roupas' 'Casa' 'Roupas' 'Roupas'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Eletrônicos' 'Casa'
 'Casa' 'Eletrônicos' 'Roupas' 'Eletrônicos' 'Casa' 'Casa' 'Roupas'
 'Eletrônicos' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa']


Passo 2: Determine o volume de vendas de cada departamento. Utilize a função np.unique habilitando o argumento return_counts=True para obter os valores únicos e suas respectivas contagens — esta é uma forma rápida de fazer o equivalente numérico de contagem de categorias.

In [ ]:
departamentos, contagens = np.unique(amostra_vendas, return_counts=True)
print('Volume de vendas por departamento:')
for dep, count in zip(departamentos, contagens):
    print(f'- {dep}: {count} vendas')

Volume de vendas por departamento:
- Casa: 21 vendas
- Eletrônicos: 12 vendas
- Roupas: 17 vendas


 Passo 3: O time de marketing enviou um array com o faturamento de cinco campanhas simultâneas: [12000, 45000, 23000, 89000, 31000]. Identifique rapidamente a campanha campeã utilizando o método que retorna o índice (posição) do maior valor do array.

In [ ]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])
indice_campea = np.argmax(faturamento_campanhas)
print(f'Faturamento das campanhas: {faturamento_campanhas}')
print(f'O índice da campanha campeã é: {indice_campea}')
print(f'O faturamento da campanha campeã é: {faturamento_campanhas[indice_campea]}')

Faturamento das campanhas: [12000 45000 23000 89000 31000]
O índice da campanha campeã é: 3
O faturamento da campanha campeã é: 89000
